---
title: "Assignment 5 - Tidy Data"
author: "mihir parikh"
date: "2/12/2018"
output:
  html_document:
    keep_md: true
---

#Data Munging
```{r yob2016 munging}
#a. read text file, set column names
df <- read.table("yob2016.txt", header = FALSE, sep = ";")
colnames(df) <- c("first name", "gender" ,"amount of children")

#b. summary and structure of data
summary(df)
str(df)
dim(df)
head(df)

#c. display bad record
rowBadRecord <- grep("yyy", df$`first name`)

#d. remove bad record
y2016 <- df[-c(rowBadRecord),]
```

#Data Merging
```{r merging}
#a. read text file and set column names
y2015 <- read.table("yob2015.txt", header = FALSE, sep = ",")
colnames(y2015) <- c("first name", "gender" ,"amount of children")

#b. display last ten rows
tail(y2015, 10)
#It is interesting that all have 5 children, indicating that 5 children maybe the cutoff to make the list.

#c. Merge data
final <- merge(y2015, y2016, by="first name")
```

#Data Summary
```{r summary}
#a. add total column
final$Total<- rowSums(final[, c(3, 5)])

#b. sorted by total
sortedFinal <- final[order(final$Total),]
tail(sortedFinal, 10)[,1]

#c. top 10 most popular girl names
girlData <- final[final$gender.x == "F",]
sortedGirlNames <- girlData[order(girlData$Total),]
top10GirlNames <- tail(sortedGirlNames, 10)
top10GirlNames[,1]

#d. write to csv
write.csv(top10GirlNames[,c("first name","Total")], file="top_10_girl_names.csv",row.names=FALSE)
```

#Github Link
https://github.com/mihir787/msds_homework/tree/master/assignment5_tidy_data